<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('students', function (Blueprint $table) {
            // Using unsignedInteger to match unsignedInteger('student_id') in users table
            $table->increments('student_id');

            // Academic & Identity Info
            $table->string('student_number', 20)->unique();
            $table->string('surname', 100)->nullable();
            $table->string('firstname', 100)->nullable();
            $table->string('middlename', 100)->nullable();
            $table->string('ext', 10)->nullable();
            $table->string('email', 100)->nullable()->unique();

            // Program / Academic Links
            $table->unsignedBigInteger('degree_id')->nullable();
            $table->unsignedBigInteger('curricula_id')->nullable();
            $table->unsignedInteger('entrance_status')->default(1);
            $table->string('rfid', 100)->nullable()->unique();

            /*
            |--------------------------------------------------------------------------
            | Form 5 Parsed Metadata Fields
            |--------------------------------------------------------------------------
            */
            $table->string('degree', 255)->nullable(); // Expanded to handle unparsed labels
            $table->string('year_section', 50)->nullable();
            $table->string('semester', 50)->nullable();
            $table->string('academic_year', 50)->nullable();

            /*
            |--------------------------------------------------------------------------
            | OCR & Facial Biometric Verification Fields
            |--------------------------------------------------------------------------
            */
            // Path to saved Form 5 PDF document in storage
            $table->string('form_5_path')->nullable();

            // Path to reference webcam snapshot in private storage
            $table->string('face_photo_path')->nullable();

            // 512-Dimensional Vector Array generated by InsightFace
            $table->json('face_embedding')->nullable();

            // Verification status tracking (ENUM updated with pending_face_verification)
            $table->enum('verification_status', [
                'pending_form5',
                'pending_face_verification',
                'pending_verification',
                'pending',
                'verified',
                'rejected',
                'manual_review'
            ])->default('pending_face_verification');

            $table->timestamps();

            // Database Indexes for Fast Search
            $table->index('verification_status');
            $table->index(['surname', 'firstname']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('students');
    }
};