name: mobile_app
description: "CCIS Student Attendance System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.11.0
  provider: ^6.1.5+1
  sqflite: ^2.4.3
  path: ^1.9.1
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.3.1
  geolocator: ^14.0.3
  permission_handler: ^13.0.1
  camera: ^0.12.0+2
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  intl: ^0.20.3
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ccis_logo.png
